// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: MainService.proto

package __

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewChainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master     string               `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	VotesCount int32                `protobuf:"varint,2,opt,name=votesCount,proto3" json:"votesCount,omitempty"`
	LimitTime  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=limitTime,proto3" json:"limitTime,omitempty"`
}

func (x *NewChainRequest) Reset() {
	*x = NewChainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChainRequest) ProtoMessage() {}

func (x *NewChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChainRequest.ProtoReflect.Descriptor instead.
func (*NewChainRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{0}
}

func (x *NewChainRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *NewChainRequest) GetVotesCount() int32 {
	if x != nil {
		return x.VotesCount
	}
	return 0
}

func (x *NewChainRequest) GetLimitTime() *timestamp.Timestamp {
	if x != nil {
		return x.LimitTime
	}
	return nil
}

type NewChainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateHelpProto *CreateHelp `protobuf:"bytes,1,opt,name=CreateHelpProto,proto3" json:"CreateHelpProto,omitempty"` //string error = 2;
}

func (x *NewChainResponse) Reset() {
	*x = NewChainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChainResponse) ProtoMessage() {}

func (x *NewChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChainResponse.ProtoReflect.Descriptor instead.
func (*NewChainResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{1}
}

func (x *NewChainResponse) GetCreateHelpProto() *CreateHelp {
	if x != nil {
		return x.CreateHelpProto
	}
	return nil
}

type CreateHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *CreateHelp) Reset() {
	*x = CreateHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHelp) ProtoMessage() {}

func (x *CreateHelp) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHelp.ProtoReflect.Descriptor instead.
func (*CreateHelp) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHelp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CallCreateVotersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// google.protobuf.Any voter = 1;
	Voter  string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Master string `protobuf:"bytes,2,opt,name=master,proto3" json:"master,omitempty"`
}

func (x *CallCreateVotersRequest) Reset() {
	*x = CallCreateVotersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallCreateVotersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCreateVotersRequest) ProtoMessage() {}

func (x *CallCreateVotersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCreateVotersRequest.ProtoReflect.Descriptor instead.
func (*CallCreateVotersRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{3}
}

func (x *CallCreateVotersRequest) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *CallCreateVotersRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type CallCreateVotersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User []*BlockchainUser `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"` //string error = 2;
}

func (x *CallCreateVotersResponse) Reset() {
	*x = CallCreateVotersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallCreateVotersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCreateVotersResponse) ProtoMessage() {}

func (x *CallCreateVotersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCreateVotersResponse.ProtoReflect.Descriptor instead.
func (*CallCreateVotersResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{4}
}

func (x *CallCreateVotersResponse) GetUser() []*BlockchainUser {
	if x != nil {
		return x.User
	}
	return nil
}

type BlockchainUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PublicKey   string `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	IsUsed      bool   `protobuf:"varint,3,opt,name=IsUsed,proto3" json:"IsUsed,omitempty"`
	Affiliation string `protobuf:"bytes,4,opt,name=Affiliation,proto3" json:"Affiliation,omitempty"`
}

func (x *BlockchainUser) Reset() {
	*x = BlockchainUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainUser) ProtoMessage() {}

func (x *BlockchainUser) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainUser.ProtoReflect.Descriptor instead.
func (*BlockchainUser) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{5}
}

func (x *BlockchainUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockchainUser) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *BlockchainUser) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

func (x *BlockchainUser) GetAffiliation() string {
	if x != nil {
		return x.Affiliation
	}
	return ""
}

type CallViewCandidatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master string `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
}

func (x *CallViewCandidatesRequest) Reset() {
	*x = CallViewCandidatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallViewCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallViewCandidatesRequest) ProtoMessage() {}

func (x *CallViewCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallViewCandidatesRequest.ProtoReflect.Descriptor instead.
func (*CallViewCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{6}
}

func (x *CallViewCandidatesRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type CallViewCandidatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElectionSubjects []*BlockchainElectionSubjects `protobuf:"bytes,1,rep,name=electionSubjects,proto3" json:"electionSubjects,omitempty"` //string error = 2;
}

func (x *CallViewCandidatesResponse) Reset() {
	*x = CallViewCandidatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallViewCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallViewCandidatesResponse) ProtoMessage() {}

func (x *CallViewCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallViewCandidatesResponse.ProtoReflect.Descriptor instead.
func (*CallViewCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{7}
}

func (x *CallViewCandidatesResponse) GetElectionSubjects() []*BlockchainElectionSubjects {
	if x != nil {
		return x.ElectionSubjects
	}
	return nil
}

type BlockchainElectionSubjects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PublicKey         string `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Description       string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	VotingAffiliation string `protobuf:"bytes,4,opt,name=VotingAffiliation,proto3" json:"VotingAffiliation,omitempty"`
}

func (x *BlockchainElectionSubjects) Reset() {
	*x = BlockchainElectionSubjects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainElectionSubjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainElectionSubjects) ProtoMessage() {}

func (x *BlockchainElectionSubjects) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainElectionSubjects.ProtoReflect.Descriptor instead.
func (*BlockchainElectionSubjects) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{8}
}

func (x *BlockchainElectionSubjects) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockchainElectionSubjects) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *BlockchainElectionSubjects) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlockchainElectionSubjects) GetVotingAffiliation() string {
	if x != nil {
		return x.VotingAffiliation
	}
	return ""
}

type CallNewCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Affiliation string `protobuf:"bytes,2,opt,name=affiliation,proto3" json:"affiliation,omitempty"`
}

func (x *CallNewCandidateRequest) Reset() {
	*x = CallNewCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallNewCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallNewCandidateRequest) ProtoMessage() {}

func (x *CallNewCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallNewCandidateRequest.ProtoReflect.Descriptor instead.
func (*CallNewCandidateRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{9}
}

func (x *CallNewCandidateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CallNewCandidateRequest) GetAffiliation() string {
	if x != nil {
		return x.Affiliation
	}
	return ""
}

type CallNewCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElectionSubjects *BlockchainElectionSubjects `protobuf:"bytes,1,opt,name=electionSubjects,proto3" json:"electionSubjects,omitempty"` //string error = 2;
}

func (x *CallNewCandidateResponse) Reset() {
	*x = CallNewCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallNewCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallNewCandidateResponse) ProtoMessage() {}

func (x *CallNewCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallNewCandidateResponse.ProtoReflect.Descriptor instead.
func (*CallNewCandidateResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{10}
}

func (x *CallNewCandidateResponse) GetElectionSubjects() *BlockchainElectionSubjects {
	if x != nil {
		return x.ElectionSubjects
	}
	return nil
}

type WinnersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master string `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
}

func (x *WinnersListRequest) Reset() {
	*x = WinnersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WinnersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnersListRequest) ProtoMessage() {}

func (x *WinnersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnersListRequest.ProtoReflect.Descriptor instead.
func (*WinnersListRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{11}
}

func (x *WinnersListRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type WinnersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElectionList []*ContractElectionsList `protobuf:"bytes,1,rep,name=electionList,proto3" json:"electionList,omitempty"` //string error = 2;
}

func (x *WinnersListResponse) Reset() {
	*x = WinnersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WinnersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnersListResponse) ProtoMessage() {}

func (x *WinnersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnersListResponse.ProtoReflect.Descriptor instead.
func (*WinnersListResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{12}
}

func (x *WinnersListResponse) GetElectionList() []*ContractElectionsList {
	if x != nil {
		return x.ElectionList
	}
	return nil
}

type ContractElectionsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElectionSubjects *BlockchainElectionSubjects `protobuf:"bytes,1,opt,name=electionSubjects,proto3" json:"electionSubjects,omitempty"`
	Balance          string                      `protobuf:"bytes,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *ContractElectionsList) Reset() {
	*x = ContractElectionsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractElectionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractElectionsList) ProtoMessage() {}

func (x *ContractElectionsList) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractElectionsList.ProtoReflect.Descriptor instead.
func (*ContractElectionsList) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{13}
}

func (x *ContractElectionsList) GetElectionSubjects() *BlockchainElectionSubjects {
	if x != nil {
		return x.ElectionSubjects
	}
	return nil
}

func (x *ContractElectionsList) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type SoloWinnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master string `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
}

func (x *SoloWinnerRequest) Reset() {
	*x = SoloWinnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoloWinnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoloWinnerRequest) ProtoMessage() {}

func (x *SoloWinnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoloWinnerRequest.ProtoReflect.Descriptor instead.
func (*SoloWinnerRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{14}
}

func (x *SoloWinnerRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type SoloWinnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElectionList *ContractElectionsList `protobuf:"bytes,1,opt,name=electionList,proto3" json:"electionList,omitempty"` //string error = 2;
}

func (x *SoloWinnerResponse) Reset() {
	*x = SoloWinnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoloWinnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoloWinnerResponse) ProtoMessage() {}

func (x *SoloWinnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoloWinnerResponse.ProtoReflect.Descriptor instead.
func (*SoloWinnerResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{15}
}

func (x *SoloWinnerResponse) GetElectionList() *ContractElectionsList {
	if x != nil {
		return x.ElectionList
	}
	return nil
}

type ChainSizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master string `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
}

func (x *ChainSizeRequest) Reset() {
	*x = ChainSizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSizeRequest) ProtoMessage() {}

func (x *ChainSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSizeRequest.ProtoReflect.Descriptor instead.
func (*ChainSizeRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{16}
}

func (x *ChainSizeRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type ChainSizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size string `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"` //string error = 2;
}

func (x *ChainSizeResponse) Reset() {
	*x = ChainSizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSizeResponse) ProtoMessage() {}

func (x *ChainSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSizeResponse.ProtoReflect.Descriptor instead.
func (*ChainSizeResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{17}
}

func (x *ChainSizeResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type GetPartOfChainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master string `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
}

func (x *GetPartOfChainRequest) Reset() {
	*x = GetPartOfChainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartOfChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartOfChainRequest) ProtoMessage() {}

func (x *GetPartOfChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartOfChainRequest.ProtoReflect.Descriptor instead.
func (*GetPartOfChainRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{18}
}

func (x *GetPartOfChainRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

type GetPartOfChainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*BlockchainBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"` //string error = 2;
}

func (x *GetPartOfChainResponse) Reset() {
	*x = GetPartOfChainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartOfChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartOfChainResponse) ProtoMessage() {}

func (x *GetPartOfChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartOfChainResponse.ProtoReflect.Descriptor instead.
func (*GetPartOfChainResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{19}
}

func (x *GetPartOfChainResponse) GetBlocks() []*BlockchainBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type BlockchainBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrHash     string                   `protobuf:"bytes,1,opt,name=CurrHash,proto3" json:"CurrHash,omitempty"`
	PrevHash     string                   `protobuf:"bytes,2,opt,name=PrevHash,proto3" json:"PrevHash,omitempty"`
	TimeStamp    *timestamp.Timestamp     `protobuf:"bytes,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Transactions []*BlockchainTransaction `protobuf:"bytes,4,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	BalanceMap   map[string]int64         `protobuf:"bytes,5,rep,name=BalanceMap,proto3" json:"BalanceMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Nonce        int64                    `protobuf:"varint,6,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Difficulty   int64                    `protobuf:"varint,7,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	ChainMaster  string                   `protobuf:"bytes,8,opt,name=ChainMaster,proto3" json:"ChainMaster,omitempty"`
}

func (x *BlockchainBlock) Reset() {
	*x = BlockchainBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainBlock) ProtoMessage() {}

func (x *BlockchainBlock) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainBlock.ProtoReflect.Descriptor instead.
func (*BlockchainBlock) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{20}
}

func (x *BlockchainBlock) GetCurrHash() string {
	if x != nil {
		return x.CurrHash
	}
	return ""
}

func (x *BlockchainBlock) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *BlockchainBlock) GetTimeStamp() *timestamp.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *BlockchainBlock) GetTransactions() []*BlockchainTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BlockchainBlock) GetBalanceMap() map[string]int64 {
	if x != nil {
		return x.BalanceMap
	}
	return nil
}

func (x *BlockchainBlock) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BlockchainBlock) GetDifficulty() int64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *BlockchainBlock) GetChainMaster() string {
	if x != nil {
		return x.ChainMaster
	}
	return ""
}

type BlockchainTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandBytes []byte `protobuf:"bytes,1,opt,name=RandBytes,proto3" json:"RandBytes,omitempty"`
	PrevBlock string `protobuf:"bytes,2,opt,name=PrevBlock,proto3" json:"PrevBlock,omitempty"`
	Sender    string `protobuf:"bytes,3,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver  string `protobuf:"bytes,4,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	Value     int64  `protobuf:"varint,5,opt,name=Value,proto3" json:"Value,omitempty"`
	Signature string `protobuf:"bytes,6,opt,name=Signature,proto3" json:"Signature,omitempty"`
	CurrHash  string `protobuf:"bytes,7,opt,name=CurrHash,proto3" json:"CurrHash,omitempty"`
}

func (x *BlockchainTransaction) Reset() {
	*x = BlockchainTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTransaction) ProtoMessage() {}

func (x *BlockchainTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTransaction.ProtoReflect.Descriptor instead.
func (*BlockchainTransaction) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{21}
}

func (x *BlockchainTransaction) GetRandBytes() []byte {
	if x != nil {
		return x.RandBytes
	}
	return nil
}

func (x *BlockchainTransaction) GetPrevBlock() string {
	if x != nil {
		return x.PrevBlock
	}
	return ""
}

func (x *BlockchainTransaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *BlockchainTransaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *BlockchainTransaction) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BlockchainTransaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BlockchainTransaction) GetCurrHash() string {
	if x != nil {
		return x.CurrHash
	}
	return ""
}

type GetFullChainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*BlockchainBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"` //string error = 2;
}

func (x *GetFullChainResponse) Reset() {
	*x = GetFullChainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullChainResponse) ProtoMessage() {}

func (x *GetFullChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullChainResponse.ProtoReflect.Descriptor instead.
func (*GetFullChainResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{22}
}

func (x *GetFullChainResponse) GetBlocks() []*BlockchainBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type AcceptLoadUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
}

func (x *AcceptLoadUserRequest) Reset() {
	*x = AcceptLoadUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptLoadUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLoadUserRequest) ProtoMessage() {}

func (x *AcceptLoadUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLoadUserRequest.ProtoReflect.Descriptor instead.
func (*AcceptLoadUserRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{23}
}

func (x *AcceptLoadUserRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AcceptLoadUserRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type AcceptLoadUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *BlockchainUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` //string error = 2;
}

func (x *AcceptLoadUserResponse) Reset() {
	*x = AcceptLoadUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptLoadUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLoadUserResponse) ProtoMessage() {}

func (x *AcceptLoadUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLoadUserResponse.ProtoReflect.Descriptor instead.
func (*AcceptLoadUserResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{24}
}

func (x *AcceptLoadUserResponse) GetUser() *BlockchainUser {
	if x != nil {
		return x.User
	}
	return nil
}

type AcceptNewUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass      string `protobuf:"bytes,1,opt,name=pass,proto3" json:"pass,omitempty"`
	Salt      string `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	PublicKey string `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *AcceptNewUserRequest) Reset() {
	*x = AcceptNewUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptNewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNewUserRequest) ProtoMessage() {}

func (x *AcceptNewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNewUserRequest.ProtoReflect.Descriptor instead.
func (*AcceptNewUserRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{25}
}

func (x *AcceptNewUserRequest) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *AcceptNewUserRequest) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *AcceptNewUserRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AcceptNewUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"` //string error = 2;
}

func (x *AcceptNewUserResponse) Reset() {
	*x = AcceptNewUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptNewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNewUserResponse) ProtoMessage() {}

func (x *AcceptNewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNewUserResponse.ProtoReflect.Descriptor instead.
func (*AcceptNewUserResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{26}
}

func (x *AcceptNewUserResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type VoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver string `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender   string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Master   string `protobuf:"bytes,3,opt,name=master,proto3" json:"master,omitempty"`
	Num      int64  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{27}
}

func (x *VoteRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *VoteRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *VoteRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *VoteRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` //string error = 2;
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MainService_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MainService_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_MainService_proto_rawDescGZIP(), []int{28}
}

func (x *VoteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_MainService_proto protoreflect.FileDescriptor

var file_MainService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x38, 0x0a,
	0x09, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c,
	0x70, 0x52, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x70, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x6c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x3f, 0x0a, 0x18, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x78, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x66,
	0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x41, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x19,
	0x43, 0x61, 0x6c, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x65, 0x0a, 0x1a, 0x43, 0x61, 0x6c, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x1a, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x56, 0x6f, 0x74, 0x69, 0x6e,
	0x67, 0x41, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x66, 0x66, 0x69, 0x6c, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5d, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x6c, 0x4e, 0x65, 0x77,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x18, 0x43, 0x61, 0x6c, 0x6c, 0x4e, 0x65, 0x77, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x2c, 0x0a, 0x12, 0x57, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x13, 0x57, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x0c, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0c, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x7a, 0x0a, 0x15, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x10, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x6f, 0x6c, 0x6f, 0x57, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x12, 0x53, 0x6f, 0x6c, 0x6f, 0x57, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0c, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22,
	0x98, 0x03, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x12, 0x38, 0x0a, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3a, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x40, 0x0a, 0x0a, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x4d, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44,
	0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x3d, 0x0a, 0x0f, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd7, 0x01, 0x0a, 0x15, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x76, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x65, 0x76, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x48, 0x61, 0x73, 0x68, 0x22, 0x40, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x55, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x4c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x3d, 0x0a,
	0x16, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5c, 0x0a, 0x14,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x15, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x22, 0x6b, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x22, 0x26, 0x0a, 0x0c, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xeb, 0x05, 0x0a, 0x08, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x12, 0x10, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x6c, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x6c,
	0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x57, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x57, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x0a, 0x53, 0x6f, 0x6c, 0x6f, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x12, 0x2e, 0x53, 0x6f, 0x6c, 0x6f, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x53, 0x6f, 0x6c, 0x6f, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x11, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74,
	0x4f, 0x66, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x15, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e,
	0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x16, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x4c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MainService_proto_rawDescOnce sync.Once
	file_MainService_proto_rawDescData = file_MainService_proto_rawDesc
)

func file_MainService_proto_rawDescGZIP() []byte {
	file_MainService_proto_rawDescOnce.Do(func() {
		file_MainService_proto_rawDescData = protoimpl.X.CompressGZIP(file_MainService_proto_rawDescData)
	})
	return file_MainService_proto_rawDescData
}

var file_MainService_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_MainService_proto_goTypes = []interface{}{
	(*NewChainRequest)(nil),            // 0: NewChainRequest
	(*NewChainResponse)(nil),           // 1: NewChainResponse
	(*CreateHelp)(nil),                 // 2: CreateHelp
	(*CallCreateVotersRequest)(nil),    // 3: CallCreateVotersRequest
	(*CallCreateVotersResponse)(nil),   // 4: CallCreateVotersResponse
	(*BlockchainUser)(nil),             // 5: BlockchainUser
	(*CallViewCandidatesRequest)(nil),  // 6: CallViewCandidatesRequest
	(*CallViewCandidatesResponse)(nil), // 7: CallViewCandidatesResponse
	(*BlockchainElectionSubjects)(nil), // 8: BlockchainElectionSubjects
	(*CallNewCandidateRequest)(nil),    // 9: CallNewCandidateRequest
	(*CallNewCandidateResponse)(nil),   // 10: CallNewCandidateResponse
	(*WinnersListRequest)(nil),         // 11: WinnersListRequest
	(*WinnersListResponse)(nil),        // 12: WinnersListResponse
	(*ContractElectionsList)(nil),      // 13: ContractElectionsList
	(*SoloWinnerRequest)(nil),          // 14: SoloWinnerRequest
	(*SoloWinnerResponse)(nil),         // 15: SoloWinnerResponse
	(*ChainSizeRequest)(nil),           // 16: ChainSizeRequest
	(*ChainSizeResponse)(nil),          // 17: ChainSizeResponse
	(*GetPartOfChainRequest)(nil),      // 18: GetPartOfChainRequest
	(*GetPartOfChainResponse)(nil),     // 19: GetPartOfChainResponse
	(*BlockchainBlock)(nil),            // 20: BlockchainBlock
	(*BlockchainTransaction)(nil),      // 21: BlockchainTransaction
	(*GetFullChainResponse)(nil),       // 22: GetFullChainResponse
	(*AcceptLoadUserRequest)(nil),      // 23: AcceptLoadUserRequest
	(*AcceptLoadUserResponse)(nil),     // 24: AcceptLoadUserResponse
	(*AcceptNewUserRequest)(nil),       // 25: AcceptNewUserRequest
	(*AcceptNewUserResponse)(nil),      // 26: AcceptNewUserResponse
	(*VoteRequest)(nil),                // 27: VoteRequest
	(*VoteResponse)(nil),               // 28: VoteResponse
	nil,                                // 29: BlockchainBlock.BalanceMapEntry
	(*timestamp.Timestamp)(nil),        // 30: google.protobuf.Timestamp
	(*empty.Empty)(nil),                // 31: google.protobuf.Empty
}
var file_MainService_proto_depIdxs = []int32{
	30, // 0: NewChainRequest.limitTime:type_name -> google.protobuf.Timestamp
	2,  // 1: NewChainResponse.CreateHelpProto:type_name -> CreateHelp
	5,  // 2: CallCreateVotersResponse.user:type_name -> BlockchainUser
	8,  // 3: CallViewCandidatesResponse.electionSubjects:type_name -> BlockchainElectionSubjects
	8,  // 4: CallNewCandidateResponse.electionSubjects:type_name -> BlockchainElectionSubjects
	13, // 5: WinnersListResponse.electionList:type_name -> ContractElectionsList
	8,  // 6: ContractElectionsList.electionSubjects:type_name -> BlockchainElectionSubjects
	13, // 7: SoloWinnerResponse.electionList:type_name -> ContractElectionsList
	20, // 8: GetPartOfChainResponse.blocks:type_name -> BlockchainBlock
	30, // 9: BlockchainBlock.TimeStamp:type_name -> google.protobuf.Timestamp
	21, // 10: BlockchainBlock.Transactions:type_name -> BlockchainTransaction
	29, // 11: BlockchainBlock.BalanceMap:type_name -> BlockchainBlock.BalanceMapEntry
	20, // 12: GetFullChainResponse.blocks:type_name -> BlockchainBlock
	5,  // 13: AcceptLoadUserResponse.user:type_name -> BlockchainUser
	0,  // 14: Contract.NewChain:input_type -> NewChainRequest
	3,  // 15: Contract.CallCreateVoters:input_type -> CallCreateVotersRequest
	9,  // 16: Contract.CallNewCandidate:input_type -> CallNewCandidateRequest
	6,  // 17: Contract.CallViewCandidates:input_type -> CallViewCandidatesRequest
	11, // 18: Contract.WinnersList:input_type -> WinnersListRequest
	14, // 19: Contract.SoloWinner:input_type -> SoloWinnerRequest
	16, // 20: Contract.ChainSize:input_type -> ChainSizeRequest
	18, // 21: Contract.GetPartOfChain:input_type -> GetPartOfChainRequest
	31, // 22: Contract.GetFullChain:input_type -> google.protobuf.Empty
	25, // 23: Contract.AcceptNewUser:input_type -> AcceptNewUserRequest
	23, // 24: Contract.AcceptLoadUser:input_type -> AcceptLoadUserRequest
	27, // 25: Contract.Vote:input_type -> VoteRequest
	1,  // 26: Contract.NewChain:output_type -> NewChainResponse
	4,  // 27: Contract.CallCreateVoters:output_type -> CallCreateVotersResponse
	10, // 28: Contract.CallNewCandidate:output_type -> CallNewCandidateResponse
	7,  // 29: Contract.CallViewCandidates:output_type -> CallViewCandidatesResponse
	12, // 30: Contract.WinnersList:output_type -> WinnersListResponse
	15, // 31: Contract.SoloWinner:output_type -> SoloWinnerResponse
	17, // 32: Contract.ChainSize:output_type -> ChainSizeResponse
	19, // 33: Contract.GetPartOfChain:output_type -> GetPartOfChainResponse
	22, // 34: Contract.GetFullChain:output_type -> GetFullChainResponse
	26, // 35: Contract.AcceptNewUser:output_type -> AcceptNewUserResponse
	24, // 36: Contract.AcceptLoadUser:output_type -> AcceptLoadUserResponse
	28, // 37: Contract.Vote:output_type -> VoteResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_MainService_proto_init() }
func file_MainService_proto_init() {
	if File_MainService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MainService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallCreateVotersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallCreateVotersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallViewCandidatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallViewCandidatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainElectionSubjects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallNewCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallNewCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WinnersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WinnersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractElectionsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoloWinnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoloWinnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainSizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainSizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPartOfChainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPartOfChainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullChainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptLoadUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptLoadUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptNewUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptNewUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MainService_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MainService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MainService_proto_goTypes,
		DependencyIndexes: file_MainService_proto_depIdxs,
		MessageInfos:      file_MainService_proto_msgTypes,
	}.Build()
	File_MainService_proto = out.File
	file_MainService_proto_rawDesc = nil
	file_MainService_proto_goTypes = nil
	file_MainService_proto_depIdxs = nil
}
